// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScenarioEntry } from "./ScenarioEntry";
import type { StyleEntry } from "./StyleEntry";

export type Catalog = { formations: Array<string>, styles: Array<StyleEntry>, scenarios: Array<ScenarioEntry>, };
