// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FrameLayout = { 
/**
 * Чисел в кадре: тик, игроки, команды, мяч.
 */
stride: number, players: number, player_fields: number, team_fields: number, ball_fields: number, players_offset: number, teams_offset: number, ball_offset: number, };
