// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FrameLayout } from "./FrameLayout";
import type { PitchInfo } from "./PitchInfo";
import type { PlayerInfo } from "./PlayerInfo";

export type MatchInfo = { seed: string, 
/**
 * `sandbox`, `scenario` или `match`.
 */
mode: string, scenario: string | null, 
/**
 * Длительность сценария в тиках; 0 у песочницы.
 */
duration_ticks: number, tick_hz: number, gait_walk_fraction: number, gait_jog_fraction: number, formations: [string, string], styles: [string, string], layout: FrameLayout, pitch: PitchInfo, players: Array<PlayerInfo>, };
