// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PitchInfo = { length_m: number, width_m: number, goal_width_m: number, goal_height_m: number, goal_depth_m: number, player_radius_m: number, ball_radius_m: number, };
