// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlayerInfo = { 
/**
 * 0 или 1.
 */
team: number, number: number, name: string, position: string, role: string, 
/**
 * Линия: 0 вратарь, 1 защита, 2 полузащита, 3 атака.
 */
line: number, height_cm: number, max_speed_ms: number, };
