// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ScenarioEntry = { id: string, description: string, formations: [string, string], styles: [string, string], duration_s: number, };
